# Banque de QCM « situation » — items originaux, style ETM (pièges, multi).
# Pas de photo scrapée. Un SVG officiel peut être ajouté dans merge_situations.py.

def Q(qid, cat, theme, question, choices, correct, explanation, slug, alt, multi=None):
    ids = [c[0] for c in choices]
    return {
        "id": qid,
        "category": cat,
        "theme": theme,
        "question": question,
        "choices": [{"id": a, "text": t} for a, t in choices],
        "correct": list(correct),
        "explanation": explanation,
        "multi": multi if multi is not None else len(correct) > 1,
        "slug": slug,
        "imageAlt": alt,
    }


ITEMS = [
    # --- Circulation ---
    Q("sit-c01", "circulation", "C",
      "À l'approche d'un giratoire à moto, qui a la priorité ?",
      [("a", "Les usagers déjà engagés dans l'anneau"),
       ("b", "Toujours ceux qui arrivent de la droite, même hors de l'anneau"),
       ("c", "Les deux-roues, par défaut"),
       ("d", "Personne : on s'arrête tous")],
      ["a"],
      "Sauf signalisation contraire, on cède à ceux déjà dans l'anneau (cédez en entrée). La priorité à droite ne s'applique pas « contre » l'anneau.",
      "rondpoint", "Giratoire vu de la chaussée"),
    Q("sit-c02", "circulation", "C",
      "Dans l'anneau, pour sortir à gauche (3/4 tour) à moto, la bonne méthode est :",
      [("a", "Voie de gauche si elle existe, clignotant gauche puis droit avant la sortie"),
       ("b", "Rester tout à droite du début à la fin"),
       ("c", "Couper en ligne droite au-dessus de l'îlot"),
       ("d", "Klaxonner et passer où il y a de la place")],
      ["a"],
      "On se place tôt, on signale, on ne rase pas l'îlot. Un motard invisible au milieu se fait couper à la sortie.",
      "carrefour-giratoire", "Giratoire à plusieurs voies"),
    Q("sit-c03", "circulation", "C",
      "Feu rouge. À moto, une seconde file de deux-roues jusqu'à la ligne :",
      [("a", "Est tolérée si la place existe, sans dépasser la ligne ni gêner"),
       ("b", "Est interdite : une seule file, toujours"),
       ("c", "Autorise à griller le rouge dès qu'il n'y a plus de voitures"),
       ("d", "Oblige à monter sur le trottoir")],
      ["a"],
      "Usage admis des deux-roues : se rabattre devant, ligne de feux respectée. Ce n'est pas un droit de filer au rouge.",
      "deux-roues-feu", "Deux-roues à un feu"),
    Q("sit-c04", "circulation", "C",
      "Le feu passe à l'orange fixe. Vous êtes encore loin du seuil :",
      [("a", "Vous devez vous arrêter, sauf si l'arrêt met en danger (déjà trop près)"),
       ("b", "L'orange est un conseil : on accélère"),
       ("c", "À moto on a le droit de passer l'orange"),
       ("d", "On s'arrête au milieu de l'intersection")],
      ["a"],
      "Orange = arrêt obligatoire si on peut le faire sans danger. Accélérer pour « sauver » l'orange est une faute classique à l'ETM.",
      "feux", "Feux tricolores en agglomération"),
    Q("sit-c05", "circulation", "C",
      "Panneau STOP. La règle stricte est :",
      [("a", "Arrêt complet, ligne, puis s'engager quand c'est libre"),
       ("b", "Ralentir à 10 km/h suffit si on voit loin"),
       ("c", "Les motos peuvent « filer » s'il n'y a personne"),
       ("d", "S'arrêter après la ligne pour mieux voir")],
      ["a"],
      "Roue arrêtée avant la ligne. Un quasi-stop (pied à terre sans arrêt franc) est sanctionné à l'examen et en circulation.",
      "stop", "Intersection avec STOP"),
    Q("sit-c06", "circulation", "C",
      "Cédez-le-passage (AB3a). Vous devez :",
      [("a", "Ralentir, laisser passer ceux de l'axe prioritaire, vous engager sans les gêner"),
       ("b", "Marquer un arrêt complet dans tous les cas"),
       ("c", "Klaxonner puis passer"),
       ("d", "Passer si vous êtes à moto : plus étroit donc prioritaire")],
      ["a"],
      "Pas d'arrêt obligatoire s'il n'y a personne, mais l'allure doit permettre de s'arrêter. Gêner un prioritaire = faute.",
      "cedez", "Cédez-le-passage à une intersection"),
    Q("sit-c07", "circulation", "C",
      "Le panneau B15 (rond, flèches rouge et noire) signifie :",
      [("a", "L'autre sens a la priorité dans le rétrécissement ; vous attendez"),
       ("b", "Vous avez la priorité : c'est l'autre qui cède"),
       ("c", "Alternat : on passe un sur deux sans regarder"),
       ("d", "Sens unique temporaire")],
      ["a"],
      "B15 : on cède aux véhicules venant en face. Le panneau inverse (B2c / flèche) donne la priorité. Piège fréquent.",
      "cedez-inverse", "Rétrécissement, cédez au sens inverse"),
    Q("sit-c08", "circulation", "C",
      "Passage piéton sans feux. Un piéton manifeste l'intention de traverser :",
      [("a", "Vous devez lui céder le passage"),
       ("b", "Seulement s'il a déjà un pied sur les bandes"),
       ("c", "À moto on le contourne par la gauche"),
       ("d", "On accélère pour passer avant")],
      ["a"],
      "R.412-38 : céder à tout piéton s'engageant régulièrement ou manifestant clairement l'intention. Contourner = très dangereux.",
      "pieton", "Passage piéton en ville"),
    Q("sit-c09", "circulation", "C",
      "Vous doublez un cycliste. Ligne continue, visibilité bonne. En France :",
      [("a", "Franchir la continue est possible pour dépasser un cycle, si la visibilité le permet et sans danger"),
       ("b", "Interdit dans tous les cas de franchir une continue"),
       ("c", "On double à 50 cm, c'est assez"),
       ("d", "On klaxonne : le cycliste doit se ranger")],
      ["a"],
      "Exception R.412-19 : dépassement d'un cycle en franchissant une continue si visibilité suffisante. Distance latérale : 1 m en agglo, 1,50 m hors agglo.",
      "ligne-continue", "Ligne continue sur chaussée"),
    Q("sit-c10", "circulation", "C",
      "Distance latérale mini pour dépasser un cycliste hors agglomération :",
      [("a", "1,50 m"),
       ("b", "50 cm"),
       ("c", "1 m"),
       ("d", "Aucun minimum à moto")],
      ["a"],
      "1 m en agglo, 1,50 m hors agglo. À moto on a tendance à « frôler » : c'est une faute et un risque de déport du vélo.",
      "velo-ville", "Cycliste en circulation"),
    Q("sit-c11", "circulation", "C",
      "Circulation inter-files (R.412-11-3), depuis janvier 2025. Elle est légale :",
      [("a", "Sur autoroutes et routes à chaussées séparées ≥ 2 voies, VMA légale ≥ 70 km/h (même abaissée localement)"),
       ("b", "Dans toutes les rues de centre-ville"),
       ("c", "Uniquement le week-end"),
       ("d", "Entre n'importe quelles files, y compris à droite")],
      ["a"],
      "Entre les 2 files les plus à gauche, files ininterrompues, 50 km/h max (30 si une file à l'arrêt). Pas en rue à une voie.",
      "interfiles", "Circulation dense, files de véhicules"),
    Q("sit-c12", "circulation", "C",
      "En inter-files, votre vitesse max est :",
      [("a", "50 km/h, et 30 km/h si une des files est à l'arrêt"),
       ("b", "70 km/h comme la VMA"),
       ("c", "90 km/h s'il n'y a pas de radar"),
       ("d", "Illimitée : on « fluidifie »")],
      ["a"],
      "Plafond CIF 50, 30 si file à l'arrêt. On réinsère dès qu'une file accélère au-delà de votre allure.",
      "file-autoroute", "Files denses sur voie rapide"),
    Q("sit-c13", "circulation", "C",
      "Insertion sur autoroute à moto. Vous devez :",
      [("a", "Prendre de la vitesse sur la bretelle, clignotant, trou de place, ne pas vous arrêter au bout"),
       ("b", "Vous arrêter en bout de bretelle et attendre un « trou » à 0 km/h"),
       ("c", "Couper directement la voie de gauche"),
       ("d", "Rentrer à 50 km/h, les autres freineront")],
      ["a"],
      "C'est vous qui vous insérez. Un arrêt en bout de bretelle à moto est un piège (arrière non vu + écart de vitesse).",
      "insertion", "Bretelle d'insertion"),
    Q("sit-c14", "circulation", "C",
      "Bande d'arrêt d'urgence. Elle sert :",
      [("a", "Uniquement à l'arrêt d'urgence / dépannage, pas à rouler ni à l'inter-files"),
       ("b", "De voie de dépassement à moto"),
       ("c", "De file de droite pour les 50 cm³"),
       ("d", "À s'arrêter pique-niquer")],
      ["a"],
      "Circuler sur la BAU = infraction. On s'y arrête seulement si on ne peut pas faire autrement, gilet + triangle selon le cas.",
      "bau", "Bande d'arrêt d'urgence"),
    Q("sit-c15", "circulation", "C",
      "Dans un tunnel, à moto :",
      [("a", "Feux allumés, distance, pas de demi-tour ni de marche arrière"),
       ("b", "On double librement : pas de radar"),
       ("c", "On retire le casque s'il fait chaud"),
       ("d", "On s'arrête sur la chaussée pour une photo")],
      ["a"],
      "Éclairage obligatoire, interdictions spécifiques (retournement). En cas d'arrêt, se ranger dans une échancrure, jamais au milieu.",
      "tunnel", "Tunnel routier"),
    Q("sit-c16", "circulation", "C",
      "Voie de bus signalée. Un motard :",
      [("a", "N'y circule pas, sauf mention « motos admises » ou desserte autorisée"),
       ("b", "Y a toujours le droit, c'est un deux-roues"),
       ("c", "Y stationne 5 minutes"),
       ("d", "Y fait de l'inter-files légal")],
      ["a"],
      "Sauf panonceau, la voie bus est réservée. L'ETM piège souvent « les motos ont le droit partout ».",
      "bus", "Voie réservée bus"),
    Q("sit-c17", "circulation", "C",
      "Rails de tram sur la chaussée. Le risque principal à moto :",
      [("a", "Glissade / guidonnage si on les prend dans l'axe, surtout mouillés"),
       ("b", "Amende automatique"),
       ("c", "Interdiction de les traverser"),
       ("d", "Ils améliorent l'adhérence")],
      ["a"],
      "On les franchit le plus perpendiculaire possible, allure réduite, sans braquer dessus. Peinture + pluie = encore pire.",
      "tram", "Rails de tramway dans la chaussée"),
    Q("sit-c18", "circulation", "C",
      "Dépassement d'un poids lourd. Vous :",
      [("a", "Restez hors de l'angle mort, vous vous montrez dans son rétro, vous doublez franchement, vous ne stagnez pas à côté"),
       ("b", "Vous collez au flanc droit, « il vous voit »"),
       ("c", "Vous doublez par la BAU"),
       ("d", "Vous restez 200 m à sa hauteur pour discuter")],
      ["a"],
      "Si vous ne voyez pas le chauffeur, il ne vous voit pas. Un PL qui change de voie à 90 km/h n'a pas le temps de vous éviter.",
      "pl", "Poids lourd sur route"),
    Q("sit-c19", "circulation", "C",
      "Sortie d'autoroute. Vous devez :",
      [("a", "Anticiper, file de droite tôt, ralentir sur la bretelle, pas sur la voie principale au dernier moment"),
       ("b", "Freiner à fond sur la voie de gauche puis couper"),
       ("c", "Faire demi-tour sur la BAU si vous avez raté"),
       ("d", "Reculer sur la bretelle")],
      ["a"],
      "Rater une sortie : on va à la suivante. Reculer / BAU = très dangereux et interdit.",
      "sortie", "Sortie d'autoroute"),
    Q("sit-c20", "circulation", "C",
      "Sens interdit. Vous pouvez :",
      [("a", "Ne pas y entrer, même « juste 20 m » pour un stationnement"),
       ("b", "Y passer à moto, plus étroit"),
       ("c", "Y entrer en reculant"),
       ("d", "Y circuler le dimanche")],
      ["a"],
      "B1 = interdiction dans le sens indiqué. Pas d'exception moto.",
      "sens-interdit", "Rue en sens interdit"),
    Q("sit-c21", "circulation", "C",
      "Zone 30. Votre allure à moto :",
      [("a", "30 km/h max, même si « ça roule à 40 »"),
       ("b", "50 : c'est encore l'agglo"),
       ("c", "70 hors écoles"),
       ("d", "Libre la nuit")],
      ["a"],
      "La zone 30 s'impose à tous. L'ETM aime le piège « en moto on peut 40, on est stable ».",
      "zone30", "Zone 30 en agglomération"),
    Q("sit-c22", "circulation", "C",
      "En agglomération, hors autre signalisation, la vitesse max est :",
      [("a", "50 km/h"),
       ("b", "70 km/h"),
       ("c", "30 km/h partout"),
       ("d", "80 km/h le soir")],
      ["a"],
      "50 en agglo (EB10). 30 seulement si zone / rue limitée. Ne pas confondre avec la hors-agglo à 80.",
      "agglomeration", "Entrée d'agglomération"),
    Q("sit-c23", "circulation", "C",
      "Fin d'agglomération, route à 2 sens sans autre panneau. Vitesse max :",
      [("a", "80 km/h (90 seulement si dérogation départementale fléchée)"),
       ("b", "90 km/h partout depuis 2018"),
       ("c", "110 km/h"),
       ("d", "50 km/h encore 2 km")],
      ["a"],
      "R.413-2 : 80 hors agglo bidirectionnelle. 90 uniquement si l'assemblée départementale a relevé ET signalé.",
      "fin-agglo", "Sortie d'agglomération"),
    Q("sit-c24", "circulation", "C",
      "Sur autoroute sèche limitée à 130, il pleut. Votre max :",
      [("a", "110 km/h"),
       ("b", "130 km/h : le panneau n'a pas changé"),
       ("c", "100 km/h"),
       ("d", "90 km/h")],
      ["a"],
      "Pluie : 110 sur autoroute (100 sur voie rapide 110, 80 hors agglo). Le panneau 130 ne « gagne » pas contre la règle pluie.",
      "pluie", "Chaussée mouillée / pluie"),
    Q("sit-c25", "circulation", "C",
      "Péage. À moto, le bon réflexe :",
      [("a", "File adaptée si elle existe, allure très réduite, sol souvent lisse / ornières"),
       ("b", "Zigzag entre les barrières"),
       ("c", "S'arrêter après la barrière en travers"),
       ("d", "Passer à 50 pour ne pas se faire rattraper")],
      ["a"],
      "Peinture + traces de pneus + rails au sol = glisse. On lâche tôt, regard loin, pas de braquage sec.",
      "peage", "Gare de péage"),
    Q("sit-c26", "circulation", "C",
      "Chantier sur le bord, véhicule avec feux de détresse. Le corridor de sécurité (R.412-11-1) impose :",
      [("a", "Ralentir, s'éloigner, changer de voie si possible"),
       ("b", "Klaxonner et maintenir sa vitesse"),
       ("c", "S'arrêter sur la voie de gauche"),
       ("d", "Doubler au plus près pour « passer vite »")],
      ["a"],
      "Depuis 2025 les SR53 le rappellent tous les 300 m. Frôler une dépanneuse = risque majeur à moto.",
      "corridor", "Véhicule / chantier en bord de voie"),
    Q("sit-c27", "circulation", "C",
      "Sens unique. Un motard :",
      [("a", "Respecte le sens, peut se déporter pour voir / être vu mais sans prendre le sens inverse"),
       ("b", "Peut remonter à contre-sens « c'est plus court »"),
       ("c", "Ignore les rues en sens unique la nuit"),
       ("d", "A le droit de stationner en double sens")],
      ["a"],
      "Le sens unique s'applique aux motos. Se placer légèrement décalé pour la visibilité ≠ remonter à contre-sens.",
      "sens-unique", "Rue à sens unique"),
    Q("sit-c28", "circulation", "C",
      "Tourner à gauche à une intersection à moto. Vous :",
      [("a", "Vous placez tôt, clignotant, contrôle d'angle mort, trajectoire claire, vous ne coupez pas"),
       ("b", "Vous serrez à droite puis vous traversez au dernier moment"),
       ("c", "Vous passez à droite des files qui attendent"),
       ("d", "Vous n'utilisez jamais le clignotant : trop d'info")],
      ["a"],
      "Le piège « se faufiler à droite puis couper » est une cause classique d'accrochage. À moto on se montre tôt.",
      "tourne-gauche", "Intersection, manœuvre vers la gauche"),

    # --- Route ---
    Q("sit-r01", "route", "R",
      "Chaussée mouillée. L'adhérence à moto :",
      [("a", "Baisse surtout au freinage et à l'inclinaison ; on allonge les distances"),
       ("b", "S'améliore : l'eau refroidit le pneu"),
       ("c", "Ne change que plus de 130 km/h"),
       ("d", "Oblige à se mettre sur l'angle max pour « sécher »")],
      ["a"],
      "Le premier quart d'heure de pluie est le pire (huile + poussière). On lisse gaz et frein, on évite les bandes blanches.",
      "pluie", "Route mouillée"),
    Q("sit-r02", "route", "R",
      "Flaque d'eau en travers. Vous :",
      [("a", "Ralentissez avant, vous la franchissez droit, sans braquer ni freiner dessus"),
       ("b", "Vous freinez fort dedans"),
       ("c", "Vous l'évitez d'un coup de guidon à 90 km/h"),
       ("d", "Vous accélérez pour « aquaplaner moins »")],
      ["a"],
      "Aquaplanage : pneu qui flotte. Guidon droit, gaz stable. Un écart de dernière seconde à moto = chute.",
      "flaque", "Flaque sur la chaussée"),
    Q("sit-r03", "route", "R",
      "Feuilles humides en virage :",
      [("a", "Adhérence proche du verglas ; on relâche l'angle et la vitesse avant"),
       ("b", "Ça accroche mieux qu'un bitume neuf"),
       ("c", "Sans effet sous 80 km/h"),
       ("d", "On accélère pour les chasser")],
      ["a"],
      "Feuilles + pluie = piège. On les traite comme une plaque de glace.",
      "feuilles", "Feuilles sur la chaussée"),
    Q("sit-r04", "route", "R",
      "Verglas possible (ombre d'un pont, matin). Vous :",
      [("a", "Réduisez très tôt, évitez les appuis, pas de freinage brusque"),
       ("b", "Freinez fort pour « tester »"),
       ("c", "Penchez plus pour mettre du pneu neuf"),
       ("d", "Ignorez : le bitume français ne gèle pas")],
      ["a"],
      "Le verglas se voit mal. Les zones d'ombre et les ponts gèlent en premier. À moto, un test de frein = chute.",
      "verglas", "Route hivernale / risque de glace"),
    Q("sit-r05", "route", "R",
      "Brouillard dense sur voie rapide. Vous :",
      [("a", "Allumez les feux adaptés, réduisez, augmentez les distances, pas de dépassement hasardeux"),
       ("b", "Feux de route pour « percer »"),
       ("c", "Vitesse inchangée : le GPS guide"),
       ("d", "Suivez au plus près les feux du véhicule devant")],
      ["a"],
      "Feux de brouillard selon l'équipement / la visibilité, jamais les route dans le brouillard (éblouissement). Distance de sécurité x2.",
      "brouillard", "Circulation dans le brouillard"),
    Q("sit-r06", "route", "R",
      "Neige / chaussée blanche. À moto :",
      [("a", "Souvent le bon choix est de ne pas partir ; sinon allure très réduite, traces existantes"),
       ("b", "Les pneus moto « hivernaux » autorisent 130"),
       ("c", "On se met sur l'angle pour mordre la neige"),
       ("d", "On suit un PL au plus près : il « ouvre »")],
      ["a"],
      "Une moto n'a pas de stabilité auto. L'ETM attend qu'on sache renoncer.",
      "neige", "Route enneigée"),
    Q("sit-r07", "route", "R",
      "Virage de montagne, visibilité courte. Vous :",
      [("a", "Ralentissez avant le virage, regard à la corde / sortie, restez sur votre voie"),
       ("b", "Coupez à gauche pour « voir plus tôt »"),
       ("c", "Accélérez : plus on va vite, plus c'est stable"),
       ("d", "Klaxonnez en continu")],
      ["a"],
      "Trajectoire de sécurité : extérieur-intérieur-extérieur, sans mordre l'axe. Un bus en face n'a pas de place pour vous.",
      "virage", "Virage sur route de montagne"),
    Q("sit-r08", "route", "R",
      "Dos-d'âne. À moto :",
      [("a", "On ralentit franchement, on se relève un peu, on évite de sauter"),
       ("b", "On l'attaque à 50 pour « l'avaler »"),
       ("c", "On le prend sur l'angle"),
       ("d", "On le contourne par le trottoir")],
      ["a"],
      "Un saut décolle la roue avant : plus de direction. Trottoir = infraction + piéton.",
      "dosane", "Ralentisseur / dos-d'âne"),
    Q("sit-r09", "route", "R",
      "Chaussée dégradée / nids-de-poule. Vous :",
      [("a", "Réduisez, vous évitez sans écart violent, vous prévenez derrière (frein + position)"),
       ("b", "Vous les ignorez : la suspension moto suffit"),
       ("c", "Vous les visez pour « tester les pneus »"),
       ("d", "Vous changez de file sans regarder")],
      ["a"],
      "Un nid-de-poule peut pincer un pneu moto (crevaison / voile jante). L'écart sans rétro = collision arrière.",
      "degrade", "Chaussée dégradée"),
    Q("sit-r10", "route", "R",
      "Gravillons / chantier. Le risque :",
      [("a", "Perte d'adhérence au freinage et en virage ; on annonce et on lisse tout"),
       ("b", "Meilleure accroche"),
       ("c", "Aucun à moins de 90 km/h"),
       ("d", "On freine ABS à fond, ça « balaie »")],
      ["a"],
      "Les gravillons roulent sous le pneu. Freinage appuyé + angle = glisse. Panneau AK + B14 souvent associés.",
      "gravillons", "Gravillons sur la chaussée"),
    Q("sit-r11", "route", "R",
      "Marquages au sol (bandes, zébras) sous la pluie :",
      [("a", "Beaucoup plus glissants que le bitume ; on évite de freiner / pencher dessus"),
       ("b", "Plus rugueux, donc plus sûrs"),
       ("c", "Interdits aux motos"),
       ("d", "Sans effet")],
      ["a"],
      "Peinture + pluie = patinoire. On place les pneus à côté des bandes quand c'est possible.",
      "marquage", "Marquages au sol"),
    Q("sit-r12", "route", "R",
      "Rails (tram, PN). La bonne traversée :",
      [("a", "Angle le plus droit possible, allure réduite, gaz stable"),
       ("b", "Dans l'axe du rail, en glissant"),
       ("c", "Frein avant seul dessus"),
       ("d", "Angle max pour « raccourcir »")],
      ["a"],
      "Un pneu coincé dans le rail = chute immédiate. Pareil au passage à niveau.",
      "rails", "Rails dans la chaussée"),
    Q("sit-r13", "route", "R",
      "Chantier avec déviation. Vous :",
      [("a", "Respectez la signalisation temporaire (fond jaune), les vitesses et le balisage"),
       ("b", "Gardez 80 : le temporaire « ne compte pas »"),
       ("c", "Doublez les cônes par la gauche"),
       ("d", "Suivez le GPS même s'il coupe le chantier")],
      ["a"],
      "Le temporaire prime. Les plots ne sont pas une suggestion. Corridor : on s'éloigne des agents.",
      "chantier", "Chantier routier"),
    Q("sit-r14", "route", "R",
      "Contre-jour / soleil rasant. À moto :",
      [("a", "On ralentit, on augmente les distances, on se méfie des piétons et des feux moins visibles"),
       ("b", "On accélère pour « sortir de la zone »"),
       ("c", "On retire le casque"),
       ("d", "Sans effet : la visière suffit toujours")],
      ["a"],
      "Le soleil mange les feux et les piétons. Une visière teintée la nuit est interdite / dangereuse, le jour elle n'annule pas l'éblouissement.",
      "soleil", "Route en contre-jour"),
    Q("sit-r15", "route", "R",
      "Nuit, éclairage public faible. Vous :",
      [("a", "Feux en état, allure adaptée à la portée des phares, méfiance des non-éclairés"),
       ("b", "Même vitesse qu'en plein jour : « je connais la route »"),
       ("c", "Feux de route en ville face aux autres"),
       ("d", "Un seul feu suffit même s'il est HS")],
      ["a"],
      "On ne roule que dans ce qu'on éclaire. Feux de route hors agglo s'il n'y a personne en face.",
      "nuit", "Circulation de nuit"),

    # --- Signalisation (en situation) ---
    Q("sit-s01", "signalisation", "R",
      "Le panneau d'entrée d'agglo (nom de commune) emporte surtout :",
      [("a", "50 km/h et les règles d'agglo (sauf autre panneau)"),
       ("b", "Uniquement une info touristique"),
       ("c", "L'obligation de klaxonner"),
       ("d", "L'interdiction de s'arrêter 2 km")],
      ["a"],
      "EB10 = début d'agglomération. C'est une vraie limite, pas une déco.",
      "agglomeration", "Panneau d'entrée d'agglomération"),
    Q("sit-s02", "signalisation", "R",
      "Panneau de travaux (fond jaune). Il :",
      [("a", "Prime sur la signalisation permanente le temps du chantier"),
       ("b", "Est indicatif"),
       ("c", "Ne concerne pas les motos"),
       ("d", "Autorise 10 km/h de plus pour « dégager »")],
      ["a"],
      "Temporaire > permanent. AK + limitations B14 jaunes : on applique.",
      "travaux-panneau", "Signalisation de travaux"),
    Q("sit-s03", "signalisation", "R",
      "Un radar / panneau de contrôle automatisé annonce :",
      [("a", "Un contrôle possible : on respecte la VMA, on ne freine pas à l'absurde au dernier mètre"),
       ("b", "Qu'on peut rouler 5 km/h au-dessus sans risque"),
       ("c", "Une obligation de s'arrêter"),
       ("d", "Que les motos ne sont pas flashées")],
      ["a"],
      "Les motos sont flashées (souvent l'avant). La « marge » n'est pas un droit.",
      "radar", "Contrôle automatisé de vitesse"),
    Q("sit-s04", "signalisation", "R",
      "Priorité à droite (pas d'autre panneau). Au carrefour :",
      [("a", "Je cède à droite, je ne « saute » pas parce que je suis à moto"),
       ("b", "La moto est toujours prioritaire"),
       ("c", "Le plus gros passe"),
       ("d", "On s'ignore : chacun sa trajectoire")],
      ["a"],
      "Sans AB, sans STOP, sans feux : priorité à droite. Beaucoup d'accidents moto viennent de « je ne l'ai pas vu »… à droite.",
      "priorite-droite", "Carrefour à priorité à droite"),
    Q("sit-s05", "signalisation", "R",
      "Passage à niveau. Feux / barrières. Vous :",
      [("a", "Vous vous arrêtez dès le signal, vous ne vous faufilez jamais, vous ne stagnez pas sur les voies"),
       ("b", "Vous passez si la barre n'est pas tout à fait baissée"),
       ("c", "Vous doublez les voitures arrêtées sur les voies"),
       ("d", "Le train s'arrêtera : il vous a vu")],
      ["a"],
      "Un train ne s'arrête pas. S'engager et rester coincé est mortel. À moto, les rails + précipitation = chute.",
      "passage-pn", "Passage à niveau"),
    Q("sit-s06", "signalisation", "R",
      "Aire piétonne. Sauf exception signalée :",
      [("a", "Circulation motorisée interdite ou très encadrée (riverains / 6 km/h selon le régime)"),
       ("b", "Les motos ont toujours le droit à 30"),
       ("c", "On peut y faire du slalom pédagogique"),
       ("d", "C'est une zone 50 déguisée")],
      ["a"],
      "B54 / régime local. On ne « coupe » pas une aire piétonne pour gagner 2 minutes.",
      "aire-pietonne", "Zone piétonne"),
    Q("sit-s07", "signalisation", "R",
      "Fin d'autoroute. Ensuite, sauf nouveau panneau :",
      [("a", "On n'est plus au régime autoroutier (130, BAU, etc.)"),
       ("b", "On garde 130 jusqu'au prochain village"),
       ("c", "Inter-files encore 10 km"),
       ("d", "On peut faire demi-tour sur la chaussée")],
      ["a"],
      "C107/C207 : fin. On relit la VMA et le type de voie. Beaucoup se font flasher juste après.",
      "fin-autoroute", "Fin d'autoroute"),
    Q("sit-s08", "signalisation", "R",
      "Panneau animaux / gibier. Vous :",
      [("a", "Réduisez, surtout à l'aube / crépuscule, prêt à un écart de l'animal"),
       ("b", "Accélérez pour « passer la zone »"),
       ("c", "Klaxonnez en continu 2 km"),
       ("d", "Ignorez : c'est décoratif")],
      ["a"],
      "Un sanglier de 80 kg à moto = chute grave. On lève le pied, on couvre le frein.",
      "faune", "Signalisation d'animaux"),
    Q("sit-s09", "signalisation", "R",
      "Ligne discontinue. Elle autorise :",
      [("a", "Le franchissement pour dépasser / changer de voie si la visibilité et les règles le permettent"),
       ("b", "N'importe quel écart, même sans visibilité"),
       ("c", "Le stationnement au milieu"),
       ("d", "Rien : c'est comme une continue")],
      ["a"],
      "Discontinue = franchissable, pas « obligatoire de doubler ». On ne double pas si un véhicule arrive.",
      "ligne-discontinue", "Ligne discontinue"),
    Q("sit-s10", "signalisation", "R",
      "Stationnement gênant (sur un passage, un trottoir utile, une piste). À moto :",
      [("a", "C'est interdit comme pour une voiture si on gêne / on masque"),
       ("b", "Les motos ont le droit partout « on prend peu de place »"),
       ("c", "Sur un passage piéton c'est autorisé 5 min"),
       ("d", "Devant un passage piéton c'est recommandé : ça protège")],
      ["a"],
      "Masquer un piéton / une piste est un classique de l'ETM. « Petite moto » n'est pas une excuse.",
      "stationnement-genant", "Véhicule gênant sur l'espace public"),
    Q("sit-s11", "signalisation", "R",
      "Les trois panneaux SR53 (corridor) sont :",
      [("a", "Indissociables : ralentir, s'éloigner, changer de voie"),
       ("b", "Uniquement décoratifs"),
       ("c", "Réservés aux PL"),
       ("d", "À ignorer s'il n'y a pas de radar")],
      ["a"],
      "Arrêté 2025. R.412-11-1. Tous les 300 m sur les voies concernées.",
      "radar-panneau", "Panneau de sécurité routière en situation"),
    Q("sit-s12", "signalisation", "R",
      "Chaussée étroite / rétrécissement. Vous :",
      [("a", "Adaptez, cédez si B15, pas de dépassement hasardeux"),
       ("b", "Accélérez pour passer avant l'autre"),
       ("c", "Prenez le trottoir"),
       ("d", "Klaxonnez : les autres reculent toujours")],
      ["a"],
      "On lit B15 / B2c. Jouer au plus rapide dans un rétrécissement à moto se termine contre un rétroviseur.",
      "chaussee-etroite", "Chaussée étroite"),

    # --- Usagers ---
    Q("sit-u01", "usagers", "U",
      "Piétons nombreux, rue animée. Votre priorité :",
      [("a", "Allure qui permet de s'arrêter, œil sur les sorties de stationnement et les traversées"),
       ("b", "Klaxon dès qu'un piéton approche du bord"),
       ("c", "50 pile, c'est légal donc sûr"),
       ("d", "Remonter le trottoir")],
      ["a"],
      "En ville le danger est latéral (portière, enfant). 50 légal ≠ 50 pertinent.",
      "pieton-ville", "Piétons en rue"),
    Q("sit-u02", "usagers", "U",
      "Abords d'école, enfants. Vous :",
      [("a", "Ralentissez fortement, vous vous attendez à un écart imprévisible"),
       ("b", "Gardez 50 : « ils ont appris le code »"),
       ("c", "Klaxonnez pour les éduquer"),
       ("d", "Doublez un bus scolaire par la droite")],
      ["a"],
      "Un enfant ne calcule pas les distances. Le bus scolaire masque. On se place pour être vu et pour voir.",
      "enfant", "Abords d'une école"),
    Q("sit-u03", "usagers", "U",
      "Camion à un carrefour. La règle d'or :",
      [("a", "Si vous ne voyez pas le chauffeur dans son rétro, il ne vous voit pas"),
       ("b", "Un PL voit mieux qu'une voiture"),
       ("c", "L'angle mort n'existe qu'à l'arrêt"),
       ("d", "Se coller au pare-chocs le fait vous remarquer")],
      ["a"],
      "Angles morts énormes. On ne stagne jamais à hauteur des essieux.",
      "angle-mort-photo", "Poids lourd et visibilité"),
    Q("sit-u04", "usagers", "U",
      "Bus à l'arrêt, portes ouvertes. Vous :",
      [("a", "Ralentissez, vous vous écartez : un piéton peut surgir devant / derrière"),
       ("b", "Doublez à 50 au ras des portes"),
       ("c", "Klaxonnez le chauffeur"),
       ("d", "Passez sur la voie en sens inverse sans regarder")],
      ["a"],
      "Le piéton « bus » ne vous cherche pas. Distance + allure de marche à côté des portes.",
      "bus-arret", "Bus à l'arrêt"),
    Q("sit-u05", "usagers", "U",
      "Cycliste qui se déporte. Vous :",
      [("a", "Vous lui laissez de la marge : nid-de-poule, portière, regard derrière"),
       ("b", "Vous le serrez pour « le recadrer »"),
       ("c", "Vous le doublez au millimètre : il est étroit"),
       ("d", "Vous le klaxonnez 3 secondes")],
      ["a"],
      "Le cycliste a le droit d'éviter un obstacle. 1 m / 1,50 m ne sont pas négociables.",
      "velo", "Piste / cycliste"),
    Q("sit-u06", "usagers", "U",
      "Trottinette sur la chaussée. Vous la traitez :",
      [("a", "Comme un usager vulnérable : distance, pas de frôlement"),
       ("b", "Comme un obstacle à chasser"),
       ("c", "Elle n'a rien à y faire : on l'ignore"),
       ("d", "On la double au ras pour l'inciter à se ranger")],
      ["a"],
      "EDP motorisés : usagers faibles. Un frôlement à 40 les envoie au sol.",
      "trottinette", "Trottinette / EDP"),
    Q("sit-u07", "usagers", "U",
      "Animal sur / près de la chaussée :",
      [("a", "On ralentit, on ne fait pas d'écart brutal, on se méfie du suivant (harde)"),
       ("b", "On accélère pour l'effrayer"),
       ("c", "On le vise : il s'écarte"),
       ("d", "On le double au contact")],
      ["a"],
      "Le second animal arrive souvent. Un écart de guidon à 80 = sortie de route.",
      "animal", "Animal près de la route"),
    Q("sit-u08", "usagers", "U",
      "Cavalier. Vous :",
      [("a", "Ralentissez beaucoup, vous élargissez, vous évitez le régime / le klaxon"),
       ("b", "Klaxonnez : le cheval a l'habitude"),
       ("c", "Doublez à 70, « il est sur le bas-côté »"),
       ("d", "Passez entre le cheval et le fossé")],
      ["a"],
      "Un cheval qui cabre jette le cavalier. Moteur souple, large, pas de bruit inutile.",
      "cavalier", "Cavalier au bord de la route"),
    Q("sit-u09", "usagers", "U",
      "Véhicule prioritaire (feux + sirène). Vous :",
      [("a", "Vous lui facilitez le passage dès que c'est sûr (serrez, éventuellement vous arrêtez)"),
       ("b", "Vous accélérez pour ne pas le gêner « devant »"),
       ("c", "Vous le suivez de près : vous « profitez »"),
       ("d", "Vous l'ignorez au feu rouge : votre feu prime")],
      ["a"],
      "On cède sans créer un autre accident. Suivre un prioritaire n'autorise pas les infractions.",
      "prioritaire", "Véhicule d'intérêt général prioritaire"),
    Q("sit-u10", "usagers", "U",
      "Portière / stationnement le long de la file. Le risque moto :",
      [("a", "L'ouverture brutale (dooring) ; on laisse une marge, on couvre le frein"),
       ("b", "Aucun : les portières ont des capteurs partout"),
       ("c", "On se colle aux voitures pour « gagner de la largeur »"),
       ("d", "On circule sur le trottoir pour éviter")],
      ["a"],
      "Le dooring est un grand classique moto / vélo. On ne rase pas la ligne de stationnement.",
      "porte-ouverte", "Véhicules stationnés le long de la chaussée"),
    Q("sit-u11", "usagers", "U",
      "Groupe de motards. Chacun :",
      [("a", "Reste maître de sa trajectoire, distance, pas de dépassement « en peloton » n'importe comment"),
       ("b", "Doit coller la roue du devant"),
       ("c", "A le droit de prendre toute la chaussée à 10"),
       ("d", "Ignore les limitations : c'est un « run »")],
      ["a"],
      "Le groupe ne crée pas de droit. Un trou dans le peloton évite l'accident en chaîne.",
      "groupe-moto", "Groupe de motards"),
    Q("sit-u12", "usagers", "U",
      "Taxi / VTC qui peut s'arrêter sans prévenir. Vous :",
      [("a", "Anticipez un arrêt / un écart vers le trottoir, surtout en ville"),
       ("b", "Le doublez au ras : il a l'habitude"),
       ("c", "Le suivez à 1 m"),
       ("d", "Klaxonnez en continu")],
      ["a"],
      "Clignotant tardif + client qui descend. On se place pour voir la portière.",
      "taxi", "Taxi en circulation urbaine"),
    Q("sit-u13", "usagers", "U",
      "Travaux, ouvriers près de la voie. Vous :",
      [("a", "Ralentissez, vous vous écartez (corridor), vous ne les frôlez pas"),
       ("b", "Gardez 80 : ils ont des gilets"),
       ("c", "Klaxonnez pour les prévenir"),
       ("d", "Passez entre les plots et le camion")],
      ["a"],
      "Un agent qui recule ne vous entend pas. Corridor + allure réduite.",
      "travaux-pieton", "Personnes au bord du chantier"),
    Q("sit-u14", "usagers", "U",
      "Trottoir : un motard peut-il y circuler pour « éviter un bouchon » ?",
      [("a", "Non"),
       ("b", "Oui sous 20 km/h"),
       ("c", "Oui s'il n'y a pas de piéton visible"),
       ("d", "Oui le dimanche")],
      ["a"],
      "Le trottoir est aux piétons. Même « doucement » c'est interdit (sauf aménagements spécifiques).",
      "trottoir", "Trottoir et piétons"),
    Q("sit-u15", "usagers", "U",
      "Vous êtes invisible dans le flux. Les bons leviers :",
      [("a", "Position sur la voie, feux, écart de vitesse raisonnable, ne pas stagner dans un angle mort"),
       ("b", "Klaxon en continu"),
       ("c", "Rouler sans casque pour « qu'on voie mon visage »"),
       ("d", "Se coller au pare-chocs avant")],
      ["a"],
      "Être vu = se placer où les rétros balayent. Le klaxon n'est pas un feu de position.",
      "moto-ville", "Moto dans la circulation urbaine"),

    # --- Conducteur ---
    Q("sit-d01", "conducteur", "L",
      "Longue autoroute, fatigue. Le bon choix :",
      [("a", "S'arrêter à une aire dès les signes (bâillements, trajectoire qui flotte)"),
       ("b", "Accélérer pour arriver plus tôt"),
       ("c", "Un café en roulant"),
       ("d", "Ouvrir la visière à 130")],
      ["a"],
      "À moto la fatigue = micro-sommeil + chute. L'aire n'est pas un luxe.",
      "fatigue-autoroute", "Aire / longue voie rapide"),
    Q("sit-d02", "conducteur", "L",
      "Alcool, permis A/A2 probatoire. Le seuil est :",
      [("a", "0,2 g/l de sang (quasi zéro verre)"),
       ("b", "0,5 g/l comme tout le monde"),
       ("c", "0,8 g/l"),
       ("d", "Pas de seuil à moto")],
      ["a"],
      "Probatoire = 0,2. Un verre peut suffire. Stupéfiants : zéro.",
      "alcool-controle", "Contrôle d'alcoolémie"),
    Q("sit-d03", "conducteur", "L",
      "Téléphone tenu en main / à l'oreille en roulant :",
      [("a", "Interdit, y compris à l'arrêt au feu dans le flux"),
       ("b", "Autorisé sous 30 km/h"),
       ("c", "Autorisé avec un casque Bluetooth tenu à la main"),
       ("d", "Autorisé pour le GPS tactile à chaque intersection")],
      ["a"],
      "Kit main-libre dans le casque : encadré. Le téléphone en main au feu est verbalisable. À moto c'est aussi un problème d'équilibre.",
      "telephone-volant", "Téléphone et conduite"),
    Q("sit-d04", "conducteur", "L",
      "Médicament avec pictogramme (orange / rouge). Vous :",
      [("a", "Vous lisez / demandez conseil : certains interdisent la conduite"),
       ("b", "Vous doublez la dose : ça « passe plus vite »"),
       ("c", "À moto ça n'agit pas : l'air réveille"),
       ("d", "C'est uniquement pour les PL")],
      ["a"],
      "Le pictogramme rouge = ne pas conduire. L'ETM le demande. L'air ne compense pas un sédatif.",
      "controle", "Contrôle / vigilance du conducteur"),
    Q("sit-d05", "conducteur", "L",
      "Pluie + visière embuée. Vous :",
      [("a", "Vous vous arrêtez au sûr pour l'aérer / Pinlock ; vous ne roulez pas en aveugle"),
       ("b", "Vous ouvrez tout et vous restez à 110"),
       ("c", "Vous retirez le casque en roulant"),
       ("d", "Vous suivez les feux du devant à 2 m")],
      ["a"],
      "Une visière opaque = yeux fermés. On s'arrête, on ne « tâte » pas à 90.",
      "equip-pluie", "Moto sous la pluie"),
    Q("sit-d06", "conducteur", "L",
      "Nuit + fatigue après une journée. Le plus juste :",
      [("a", "Reporter ou couper le trajet ; la moto ne pardonne pas un micro-sommeil"),
       ("b", "Mettre la musique plus fort"),
       ("c", "Boire un verre « pour se détendre »"),
       ("d", "Rouler sans gants pour sentir le vent")],
      ["a"],
      "Combinaison fatale : nuit × fatigue × deux-roues. L'ETM valorise le renoncement.",
      "eclairage-defaut", "Route peu éclairée de nuit"),

    # --- Protection ---
    Q("sit-p01", "protection", "P",
      "En circulation, le casque homologué :",
      [("a", "Est obligatoire, attaché, visière adaptée"),
       ("b", "Peut rester ouvert / non attaché en ville"),
       ("c", "Est facultatif au-dessus de 25 °C"),
       ("d", "Peut être un jet non homologué « le temps d'aller à la boulangerie »")],
      ["a"],
      "Jugulaire attachée. Un jet CE est légal mais moins protecteur. Pas de casque « fashion » sans homolo.",
      "casque", "Motard casqué"),
    Q("sit-p02", "protection", "P",
      "Gants homologué CE :",
      [("a", "Obligatoires pour conducteur et passager"),
       ("b", "Facultatifs au-dessus de 25 °C"),
       ("c", "Remplaçables par des mitaines vélo"),
       ("d", "Uniquement sur autoroute")],
      ["a"],
      "Depuis 2016. Les mains tapent en premier à la chute.",
      "gants-moto", "Gants de moto"),
    Q("sit-p03", "protection", "P",
      "Gilet / écharpe rétro (hors agglo, nuit / visibilité réduite) :",
      [("a", "Équipement de haute visibilité exigé hors agglo quand la visibilité est mauvaise, et recommandé souvent"),
       ("b", "Jamais utile : le phare suffit"),
       ("c", "Uniquement pour les cyclistes"),
       ("d", "Interdit : ça « excite » les automobilistes")],
      ["a"],
      "Le gilet est obligatoire dans certains cas (visibilité réduite hors agglo) et toujours une bonne idée. À ne pas confondre avec le gilet en cas d'arrêt d'urgence.",
      "gilet", "Équipement haute visibilité"),
    Q("sit-p04", "protection", "P",
      "Chaussures / bottes. Le minimum raisonnable (et souvent exigé à l'examen pratique) :",
      [("a", "Montantes, qui tiennent la cheville, pas des tongs ni des baskets basses"),
       ("b", "Tongs l'été : ça « respire »"),
       ("c", "Pieds nus en ville"),
       ("d", "Talons aiguilles : ça passe au plateau")],
      ["a"],
      "Le plateau refuse souvent les baskets basses. En chute, la cheville part en premier.",
      "bottes-moto", "Chaussures / bottes de moto"),
    Q("sit-p05", "protection", "P",
      "Blouson / airbag. L'idée juste :",
      [("a", "Protections CE (dos, épaules) fortement recommandées ; le sweat n'est pas un blouson"),
       ("b", "Un t-shirt suffit si on a le casque"),
       ("c", "L'airbag remplace le casque"),
       ("d", "Le cuir est interdit en 2026")],
      ["a"],
      "L'ETM insiste sur l'équipement complet. L'airbag complète, il ne remplace rien.",
      "moto-equipement", "Équipement du motard"),
    Q("sit-p06", "protection", "P",
      "Casque jet vs intégral. Pour un trajet rapide / autoroute :",
      [("a", "L'intégral protège le visage ; le jet est légal s'il est homologué mais moins sûr"),
       ("b", "Le jet est obligatoire"),
       ("c", "Aucun casque n'est utile au-dessus de 80"),
       ("d", "Un bonnet suffit sous le jet")],
      ["a"],
      "Homologué ≠ maximal. L'ETM aime la nuance légal / recommandé.",
      "casque-ouvert", "Casque de type jet"),

    # --- Mécanique ---
    Q("sit-m01", "mecanique", "M",
      "Pneu avant lisse / à toile. Vous :",
      [("a", "Vous ne partez pas : adhérence nulle sous la pluie, freinage HS"),
       ("b", "Vous roulez « doucement jusqu'au garage » à 90"),
       ("c", "Vous gonflez à 4 bars pour compenser"),
       ("d", "Vous ne regardez que l'arrière")],
      ["a"],
      "Le témoin d'usure / la toile = arrêt. 80 % du freinage passe par l'avant.",
      "pneu", "Pneumatique moto"),
    Q("sit-m02", "mecanique", "M",
      "Chaîne trop lâche / sèche. Risque :",
      [("a", "Saut, casse, blocage de roue arrière"),
       ("b", "Meilleure souplesse"),
       ("c", "Aucun sous 130"),
       ("d", "Uniquement une usure esthétique")],
      ["a"],
      "Hors des 2–3 cm de jeu typiques (selon modèle) : danger. Graissage après la pluie.",
      "chaine", "Transmission par chaîne"),
    Q("sit-m03", "mecanique", "M",
      "Un feu (croisement / stop) HS. Vous :",
      [("a", "Vous réparez avant de circuler : être vu / signaler le freinage"),
       ("b", "Vous partez : « c'est que l'ampoule »"),
       ("c", "Vous mettez les warnings en roulant en ville"),
       ("d", "Vous baissez la visière pour compenser")],
      ["a"],
      "Éclairage = contrôle technique mental avant chaque départ. Warnings en roulant ≠ feu de croisement.",
      "phare", "Éclairage moto"),
    Q("sit-m04", "mecanique", "M",
      "Disque / plaquettes. Un signe d'alerte :",
      [("a", "Levier qui va au guidon, disque strié profond, plaquette à témoin"),
       ("b", "Un petit bruit = toujours normal"),
       ("c", "On graisse le disque"),
       ("d", "On rallonge le levier avec du fil")],
      ["a"],
      "Frein avant HS à moto = pas d'examen et pas de route. On ne graisse jamais un disque.",
      "frein-disque", "Frein à disque"),
    Q("sit-m05", "mecanique", "M",
      "Rétroviseurs. Ils doivent :",
      [("a", "Être deux, réglés, vous montrer l'arrière et les côtés — pas vos manches"),
       ("b", "Peuvent être repliés en ville « pour passer »"),
       ("c", "Un seul suffit à moto"),
       ("d", "Servent surtout à se coiffer")],
      ["a"],
      "Contrôle + angle mort de la tête. Rétros repliés = infraction et aveugle.",
      "retro-moto", "Rétroviseurs moto"),
    Q("sit-m06", "mecanique", "M",
      "Niveau d'huile. Avant un long trajet :",
      [("a", "On vérifie à froid / selon la notice, à plat"),
       ("b", "Inutile : l'huile se consomme trop peu"),
       ("c", "On remplit jusqu'à déborder"),
       ("d", "On mélange n'importe quelle viscosité")],
      ["a"],
      "Un moteur moto qui manque d'huile grille vite. Trop d'huile = joint / embrayage en bain.",
      "huile-moteur", "Contrôle d'huile"),

    # --- Divers ---
    Q("sit-v01", "divers", "D",
      "Contrôle de police. Vous :",
      [("a", "Vous vous arrêtez au sûr, moteur, papiers, casque, vous restez courtois"),
       ("b", "Vous fuvez : « je n'ai rien »"),
       ("c", "Vous restez au milieu de la voie"),
       ("d", "Vous enlevez le casque en roulant pour parler")],
      ["a"],
      "Permis, assurance, certificat d'immatriculation. On ne discute pas sur la chaussée.",
      "controle", "Contrôle routier"),
    Q("sit-v02", "divers", "D",
      "Panne sur voie rapide. L'ordre :",
      [("a", "BAU si possible, gilet, triangle si utile/possible, se mettre derrière la glissière, appeler"),
       ("b", "Rester sur sa moto au milieu"),
       ("c", "Traverser 4 voies pour « mieux voir »"),
       ("d", "Reculer en marche arrière sur 200 m")],
      ["a"],
      "On se protège d'abord. À moto, rester assis sur la machine au bord est un mauvais réflexe.",
      "panne", "Panne en bord de voie"),
    Q("sit-v03", "divers", "D",
      "Station-service. À moto :",
      [("a", "Béquille stable, moteur coupé, pas de cigarette, on ne remplit pas un jerrican n'importe comment"),
       ("b", "On reste en selle, moteur allumé"),
       ("c", "On fume à côté : « c'est dehors »"),
       ("d", "On fait le niveau d'huile au-dessus du pistolet")],
      ["a"],
      "Moteur coupé, stabilité. Une moto qui tombe sur une pompe n'est pas un détail.",
      "essence", "Station-service"),
    Q("sit-v04", "divers", "D",
      "Stationnement moto. Le plus juste :",
      [("a", "Emplacement adapté, ne pas gêner piétons / PMR / issues, béquille stable"),
       ("b", "Sur le passage piéton : « on voit mieux la moto »"),
       ("c", "Devant le trottoir abaissé PMR"),
       ("d", "Sur la piste cyclable 2 minutes")],
      ["a"],
      "Gêner un PMR ou un passage est une faute, moto ou pas.",
      "parking", "Stationnement deux-roues"),
    Q("sit-v05", "divers", "D",
      "Contrôle technique / papiers. Pour circuler :",
      [("a", "Assurance valide + certificat d'immatriculation + permis ; CT selon le régime en vigueur du véhicule"),
       ("b", "Le permis suffit"),
       ("c", "Aucune pièce à moto"),
       ("d", "Une photo du permis sur le téléphone suffit toujours")],
      ["a"],
      "L'ETM demande les 3 papiers. Le CT moto se déploie par étapes : on ne dit pas « jamais de CT ».",
      "controle-technique", "Contrôle / démarches véhicule"),

    # --- Environnement ---
    Q("sit-e01", "environnement", "E",
      "Bouchon, moteur qui tourne 10 min. Vous :",
      [("a", "Coupez si l'arrêt se prolonge ; ça pollue et peut être verbalisé"),
       ("b", "Laissez tourner « pour l'huile »"),
       ("c", "Accélérez sur place pour chauffer les pneus"),
       ("d", "C'est demandé par le constructeur")],
      ["a"],
      "Moteur à l'arrêt inutile = pollution + bruit. On part souple pour chauffer.",
      "bouchon-ville", "Circulation congestionnée"),
    Q("sit-e02", "environnement", "E",
      "En zone naturelle / faune. Vous :",
      [("a", "Allure adaptée, pas de régime inutile, respect de la VMA même « déserte »"),
       ("b", "Vous « ouvrez » : personne n'entend"),
       ("c", "Vous sortez de la route pour une photo"),
       ("d", "Vous suivez un animal pour le filmer")],
      ["a"],
      "Bruit + vitesse = le duo que l'ETM associe à la moto. On ne quitte pas la chaussée.",
      "zone-nature", "Route en espace naturel"),
    Q("sit-e03", "environnement", "E",
      "Éco-conduite à moto, concrètement :",
      [("a", "Allure stable, anticiper, éviter les pleins gaz / pleins freins, pression pneus correcte"),
       ("b", "Couper le moteur en descente en roue libre débrayé"),
       ("c", "Gonfler les pneus à 4 bars « pour rouler loin »"),
       ("d", "Rester en 1re en ville")],
      ["a"],
      "Débrayer en descente = plus de frein moteur, danger. La pression se lit sur la moto, pas au hasard.",
      "circulation-dense", "Trafic dense"),
    Q("sit-e04", "environnement", "E",
      "Pic de pollution / restrictions. Un motard :",
      [("a", "Se renseigne : certaines circulations différenciées concernent aussi les deux-roues"),
       ("b", "Est toujours exempt"),
       ("c", "Doit doubler tout le monde pour « passer moins de temps »"),
       ("d", "Peut ignorer les ZFE")],
      ["a"],
      "ZFE / pictogrammes Crit'Air : selon la ville. Ce n'est plus « les motos ne sont pas concernées » partout.",
      "pollution", "Environnement urbain"),

    # --- Secours ---
    Q("sit-x01", "secours", "S",
      "Accident sur chaussée. L'ordre PAS :",
      [("a", "Protéger, Alerter, Secourir"),
       ("b", "Secourir d'abord, on protège après"),
       ("c", "Filmer, puis alerter"),
       ("d", "Déplacer le blessé au milieu pour le « confort »")],
      ["a"],
      "On évite le suraccident d'abord (gilet, triangle, baliser). Puis 15 / 18 / 112.",
      "accident", "Accident de la route"),
    Q("sit-x02", "secours", "S",
      "Blessé casqué, inconscient, qui respire. Le casque :",
      [("a", "On ne le retire que si on sait le faire / voies aériennes ; on ne bricole pas"),
       ("b", "On l'arrache toujours tout de suite"),
       ("c", "On le laisse même s'il ne respire plus et qu'on est formé"),
       ("d", "On le déboutonne pour le garder en souvenir")],
      ["a"],
      "Retrait de casque = geste formé (double sauveteur). Inconscient qui respire : PLS si possible, après protection.",
      "secours-accident", "Secours sur accident"),
    Q("sit-x03", "secours", "S",
      "Triangle + gilet après un arrêt d'urgence :",
      [("a", "Gilet dès que vous descendez ; triangle si vous pouvez le poser sans vous exposer"),
       ("b", "Triangle au milieu de la voie de gauche"),
       ("c", "Gilet facultatif : la moto se voit"),
       ("d", "On reste sur la moto sans gilet « pour partir plus vite »")],
      ["a"],
      "Le gilet d'abord (sur vous). Un triangle mal posé fait un second accident.",
      "triangle", "Présignalisation d'un arrêt"),
    Q("sit-x04", "secours", "S",
      "Vous alertez les secours. Le plus utile :",
      [("a", "Lieu précis, nombre de victimes, état apparent, motard / casque, ne pas raccrocher trop tôt"),
       ("b", "Juste « y'a un accident » puis vous partez"),
       ("c", "Vous donnez un faux nom"),
       ("d", "Vous attendez 20 min « pour voir si ça va »")],
      ["a"],
      "15 / 18 / 112. La localisation (borne, sortie, commune) fait gagner des minutes.",
      "samu", "Alerte des secours"),
]


def all_items():
    return ITEMS
